apiVersion: v1
kind: Pod

metadata:
  name: "mypod1"
  labels:
    app: frontend
    team: team1
    region: IN
    env: prod 

spec:
 containers:
 - name: "myc1"
   image: "vimal13/apache-webserver-php"
